/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package culecalc;

import java.util.ArrayList;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URLDecoder;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 *
 * @author TetraGen
 */
public class CuleCalc extends javax.swing.JFrame {
    
    private boolean bUseElementName;
    
    public static ArrayList<CElement> elements = new XMLReader("ElementInfo").getElements();
    /**
     * Creates new form CuleCalc
     */
    public CuleCalc() {
        initComponents();
        try{
            loadProperties();
        }catch(Exception ex){
            saveProperties();
        }
        initComboBox();
        initSettings();
        Runtime.getRuntime().addShutdownHook(new Thread()
        {
            @Override
            public void run()
            {
                saveProperties();
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jFormulaField = new javax.swing.JTextField();
        jCalculate = new javax.swing.JButton();
        jPanelElements = new javax.swing.JPanel();
        jElementList = new javax.swing.JComboBox();
        jElementName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jElementSymbol = new javax.swing.JLabel();
        jPanelSettings = new javax.swing.JPanel();
        jUseElementName = new javax.swing.JCheckBox();
        jPanelAbout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 320));
        setMinimumSize(new java.awt.Dimension(320, 320));
        setPreferredSize(new java.awt.Dimension(320, 320));

        jTabbedPaneMain.setPreferredSize(new java.awt.Dimension(320, 320));

        jCalculate.setText("Calculate");
        jCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFormulaField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jCalculate)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFormulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalculate)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Main", jPanelMain);

        jPanelElements.setLayout(null);

        jElementList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jElementListActionPerformed(evt);
            }
        });
        jPanelElements.add(jElementList);
        jElementList.setBounds(97, 20, 110, 20);

        jElementName.setText("[Element Name]");
        jPanelElements.add(jElementName);
        jElementName.setBounds(120, 170, 76, 14);

        jElementSymbol.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jElementSymbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jElementSymbol.setText("[S]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jElementSymbol)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jElementSymbol)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jElementSymbol.getAccessibleContext().setAccessibleDescription("");

        jPanelElements.add(jPanel1);
        jPanel1.setBounds(60, 50, 190, 190);

        jTabbedPaneMain.addTab("Elements", jPanelElements);

        jUseElementName.setText("Use Element Name");

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jUseElementName)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jUseElementName)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Settings", jPanelSettings);
        jPanelSettings.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("About", jPanelAbout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loadProperties(){
        try{
            Properties prop = new Properties();
            File file = new File(System.getProperty("java.class.path"));
            File dir = file.getAbsoluteFile().getParentFile();
            String path = dir.toString();
            
            File f = new File(path + "\\user.properties");
            InputStream in = new FileInputStream( f );
            
            prop.load(in);
            
            bUseElementName = Boolean.parseBoolean(prop.getProperty("UseElementName"));            
            in.close();
        }catch (Exception e ) {
            e.printStackTrace();
        }
    }
    public void saveProperties(){
        try {
            //create a properties file
            Properties props = new Properties();
            props.setProperty("UseElementName", Boolean.toString(bUseElementName));
            
            File file = new File(System.getProperty("java.class.path"));
            File dir = file.getAbsoluteFile().getParentFile();
            String path = dir.toString();
            
            File f = new File(path + "\\user.properties");
            OutputStream out = new FileOutputStream( f );
            //If you wish to make some comments 
            props.store(out, "User properties");
        }catch (Exception e ) {
            e.printStackTrace();
        }
    }
    
    private void initSettings(){
        System.out.println(bUseElementName);
        jUseElementName.setSelected(bUseElementName);
        jUseElementName.addItemListener(new ItemListener() {
        @Override
        public void itemStateChanged(ItemEvent e) {
            if(e.getStateChange() == ItemEvent.SELECTED) {
                bUseElementName = true;
                updateComboBox();
            } else {
                bUseElementName = false;
                updateComboBox();
            };
        }
        });
    }
    
    private void initComboBox(){
        jElementList.removeAllItems();
        
        elements.stream().forEach((e) -> {
            jElementList.addItem(bUseElementName ? e.getName() : e.getSymbol());
        });
        
        setElementCard(1);
        
        ItemListener itemListener;
        itemListener = (ItemEvent itemEvent) -> {
            setElementCard(jElementList.getSelectedIndex());
        };
        jElementList.addItemListener(itemListener);
    }
    
    private void updateComboBox(){
        jElementList.removeAllItems();
        System.out.println("a");
        elements.stream().forEach((e) -> {
            jElementList.addItem(bUseElementName ? e.getName() : e.getSymbol());
        });
    }
    
    private void setElementCard(int i){
        CElement e = elements.get(i);
        if(jElementList.getSelectedIndex() != i){ jElementList.setSelectedIndex(i); }
        jElementName.setText(e.getName());
        jElementSymbol.setText(e.getSymbol());
    }
    
    private void jCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculateActionPerformed
        CFormula t = new CFormula(jFormulaField.getText());
        System.out.println(t.getMass(true));
        for(int i = 0; i < t.getSize(); i++)
            System.out.println(t.getPart(i).getComposition(true));
        t.getEmpirical();
    }//GEN-LAST:event_jCalculateActionPerformed

    private void jElementListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jElementListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jElementListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuleCalc().setVisible(true);
            }
        });
    }
    
    public ArrayList<CElement> getElements(){ return this.elements; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCalculate;
    private javax.swing.JComboBox jElementList;
    public javax.swing.JLabel jElementName;
    public javax.swing.JLabel jElementSymbol;
    private javax.swing.JTextField jFormulaField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelElements;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JCheckBox jUseElementName;
    // End of variables declaration//GEN-END:variables
}
